image: python:3.8-alpine

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel


test:
  stage: test
  script:
    - echo "testing"

deploy_test_pypi:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - pip install twine
    - twine upload --repository testpypi dist/* 
    
