image: "python:3.7"

stages:
  - test


test:
  stage: test
  script:
    - pip install pytest --quiet
    - pip install -E . 
    - pytest "supernest/tests/" --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
